// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: roqueproto/roque.proto

package roqueproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoqueClient is the client API for Roque service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoqueClient interface {
	Write(ctx context.Context, opts ...grpc.CallOption) (Roque_WriteClient, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Roque_ReadClient, error)
	Stream(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Roque_StreamClient, error)
}

type roqueClient struct {
	cc grpc.ClientConnInterface
}

func NewRoqueClient(cc grpc.ClientConnInterface) RoqueClient {
	return &roqueClient{cc}
}

func (c *roqueClient) Write(ctx context.Context, opts ...grpc.CallOption) (Roque_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &Roque_ServiceDesc.Streams[0], "/roqueproto.Roque/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &roqueWriteClient{stream}
	return x, nil
}

type Roque_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*WriteResult, error)
	grpc.ClientStream
}

type roqueWriteClient struct {
	grpc.ClientStream
}

func (x *roqueWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *roqueWriteClient) CloseAndRecv() (*WriteResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roqueClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Roque_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Roque_ServiceDesc.Streams[1], "/roqueproto.Roque/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &roqueReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Roque_ReadClient interface {
	Recv() (*ReadResult, error)
	grpc.ClientStream
}

type roqueReadClient struct {
	grpc.ClientStream
}

func (x *roqueReadClient) Recv() (*ReadResult, error) {
	m := new(ReadResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roqueClient) Stream(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Roque_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Roque_ServiceDesc.Streams[2], "/roqueproto.Roque/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &roqueStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Roque_StreamClient interface {
	Recv() (*ReadResult, error)
	grpc.ClientStream
}

type roqueStreamClient struct {
	grpc.ClientStream
}

func (x *roqueStreamClient) Recv() (*ReadResult, error) {
	m := new(ReadResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoqueServer is the server API for Roque service.
// All implementations must embed UnimplementedRoqueServer
// for forward compatibility
type RoqueServer interface {
	Write(Roque_WriteServer) error
	Read(*ReadRequest, Roque_ReadServer) error
	Stream(*ReadRequest, Roque_StreamServer) error
	mustEmbedUnimplementedRoqueServer()
}

// UnimplementedRoqueServer must be embedded to have forward compatible implementations.
type UnimplementedRoqueServer struct {
}

func (UnimplementedRoqueServer) Write(Roque_WriteServer) error {
	return status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedRoqueServer) Read(*ReadRequest, Roque_ReadServer) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedRoqueServer) Stream(*ReadRequest, Roque_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRoqueServer) mustEmbedUnimplementedRoqueServer() {}

// UnsafeRoqueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoqueServer will
// result in compilation errors.
type UnsafeRoqueServer interface {
	mustEmbedUnimplementedRoqueServer()
}

func RegisterRoqueServer(s grpc.ServiceRegistrar, srv RoqueServer) {
	s.RegisterService(&Roque_ServiceDesc, srv)
}

func _Roque_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoqueServer).Write(&roqueWriteServer{stream})
}

type Roque_WriteServer interface {
	SendAndClose(*WriteResult) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type roqueWriteServer struct {
	grpc.ServerStream
}

func (x *roqueWriteServer) SendAndClose(m *WriteResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *roqueWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Roque_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoqueServer).Read(m, &roqueReadServer{stream})
}

type Roque_ReadServer interface {
	Send(*ReadResult) error
	grpc.ServerStream
}

type roqueReadServer struct {
	grpc.ServerStream
}

func (x *roqueReadServer) Send(m *ReadResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Roque_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoqueServer).Stream(m, &roqueStreamServer{stream})
}

type Roque_StreamServer interface {
	Send(*ReadResult) error
	grpc.ServerStream
}

type roqueStreamServer struct {
	grpc.ServerStream
}

func (x *roqueStreamServer) Send(m *ReadResult) error {
	return x.ServerStream.SendMsg(m)
}

// Roque_ServiceDesc is the grpc.ServiceDesc for Roque service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Roque_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roqueproto.Roque",
	HandlerType: (*RoqueServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _Roque_Write_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Roque_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stream",
			Handler:       _Roque_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "roqueproto/roque.proto",
}
